version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"
    open-pull-requests-limit: 5
    registries:
      - cloudsmith
registries:
  cloudsmith:
    type: maven-repository
    url: ${{secrets.CLOUDSMITH_REPOSITORY_URL}}
    username: ${{secrets.CLOUDSMITH_USERNAME}}
    password: ${{secrets.CLOUDSMITH_API_TOKEN}}

