version: 2
registries:
  cloudsmith:
    type: "maven-repository"
    url: "https://dl.cloudsmith.io/basic/ciara-demo/sbom-support/maven/"
    username: "${{ secrets.CLOUDSMITH_USER_NAME }}"
    password: "${{ secrets.CLOUDSMITH_API_KEY }}"
updates:
  - package-ecosystem: "maven"
    directory: "/" # The location of your pom.xml file
    schedule:
      interval: "daily"
    registries: 
      - cloudsmith
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
