version: 2
registries:
  cloudsmith:
    type: "maven-repository"
    url: "https://dl.cloudsmith.io/basic/ciara-demo/sbom-support/maven/"
    #username: "${{ secrets.DEP_CLOUDSMITH_USER_NAME }}"
    #password: "${{ secrets.DEP_CLOUDSMITH_API_KEY }}"
    username: "oauth2"
    token: "${{ secrets.DEP_CLOUDSMITH_API_KEY }}"
    replaces-base: true

updates:
  - package-ecosystem: "maven"
    directory: "/" # The location of your pom.xml file
    schedule:
      interval: "daily"
    registries: 
      - cloudsmith
    commit-message:
      prefix: "deps"
