# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

variables:
  # Cloudsmith service account slug
  SERVICE: azure_acme_service
  # The secret should be set in your pipeline library as CLOUDSMITH_SERVICE_API_KEY
  CLOUDSMITH_SERVICE_API_KEY: $(CLOUDSMITH_SERVICE_API_KEY)

pool:
  vmImage: ubuntu-latest

steps:
  # 1) Check out your code
  - checkout: self

  # 2) Create ~/.m2/settings.xml with a mirror of central (for both deps & plugins) plus credentials
  - bash: |
      mkdir -p ~/.m2
      cat > ~/.m2/settings.xml << 'EOF'
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">

        <mirrors>
          <mirror>
            <id>cloudsmith-mirror</id>
            <name>Cloudsmith mirror of central (deps & plugins)</name>
            <mirrorOf>central</mirrorOf>
            <url>https://maven.cloudsmith.io/globex-innovations/acme-nonprod/</url>
          </mirror>
        </mirrors>

        <servers>
          <server>
            <id>central</id>
            <username>${SERVICE}</username>
            <password>${CLOUDSMITH_SERVICE_API_KEY}</password>
          </server>
        </servers>
      </settings>
      EOF
    displayName: Create Maven settings.xml
    env:
      SERVICE: $(SERVICE)
      CLOUDSMITH_SERVICE_API_KEY: $(CLOUDSMITH_SERVICE_API_KEY)

  # 3) Run Maven clean deploy using that settings file
  - task: Maven@4
    displayName: Maven: clean & deploy
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean deploy'
      options: '-s $(HOME)/.m2/settings.xml -U'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
