trigger:
  - main

variables:
  # Cloudsmith service account slug
  SERVICE: azure_acme_service

  # Maven <server> id (must match <id> in pom.xml)
  CLOUDSMITH_SERVER_ID: central

  # Org / repo (not used in this script but available if you need it)
  CLOUDSMITH_ORG: globex-innovations
  CLOUDSMITH_REPO: acme-nonprod

pool:
  vmImage: ubuntu-latest

steps:
  # 1) Check out your code
  - checkout: self

  # 2) Emit a settings.xml that mirrors *central* (for deps AND plugins) to your Cloudsmith repo,
  #    and injects your credentials under the same id ("central").
  - bash: |
      mkdir -p ~/.m2
      cat > ~/.m2/settings.xml << 'EOF'
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">

        <mirrors>
          <mirror>
            <id>cloudsmith-public</id>
            <name>Cloudsmith mirror of central</name>
            <mirrorOf>central</mirrorOf>
            <url>https://maven.cloudsmith.io/globex-innovations/acme-nonprod/</url>
          </mirror>
        </mirrors>

        <servers>
          <server>
            <id>$CLOUDSMITH_SERVER_ID</id>
            <username>$SERVICE</username>
            <password>$CLOUDSMITH_API_KEY</password>
          </server>
        </servers>
      </settings>
      EOF
    displayName: Create Maven settings.xml
    env:
      # this secret should be defined in your pipeline as CLOUDSMITH_SERVICE_API_KEY
      CLOUDSMITH_API_KEY: $(CLOUDSMITH_SERVICE_API_KEY)
      SERVICE: $(SERVICE)

  # 3) Run your clean+deploy exactly as before
  - task: Maven@4
    displayName: Maven clean & deploy
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'clean deploy'
      options: '-s $(HOME)/.m2/settings.xml -U'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
