name: Fetch and Print SBOM

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  fetch-print:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Download SBOM Artifact
      uses: actions/download-artifact@v2
      with:
        name: bom.xml
        path: target

    - name: Print SBOM
      run: cat target/bom.xml
