name: Download and Print SBOM

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  download-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Configure Maven settings
      run: cp my-maven-project/.github/workflows/maven-settings.xml $HOME/.m2/settings.xml

    - name: Download SBOM
      run: |
        mvn dependency:get \
          -Dartifact=com.example:my-app:xml:1.0-SNAPSHOT:cyclonedx \
          -DremoteRepositories=https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ secrets.CLOUDSMITH_REPOSITORY_URL }}/maven/ \
          -Ddest=target/sbom.xml

    - name: Print SBOM
      run: cat target/sbom.xml
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
