name: Java CI and Deploy to Cloudsmith

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDSMITH_ORG: ciara-demo
  CLOUDSMITH_REPO: acme-nonprod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up Java (here JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      # 3) Clear local Maven cache (optional)
      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository/*

      # 4) Configure Maven settings with Cloudsmith credentials
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <!-- Must match the <id> in distributionManagement of pom.xml -->
                <id>cloudsmith</id>
                <!-- 'username' can be literally 'cloudsmith' or your username -->
                <username>cloudsmith</username>
                <!-- 'password' is your Cloudsmith API Key -->
                <password>${{ secrets.CLOUDSMITH_API_KEY }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 5) Build and Deploy to Cloudsmith
      - name: Build and Deploy
        run: mvn clean deploy --settings ~/.m2/settings.xml -U
        # '-U' forces update of snapshots/releases, optional
