name: Java CI with mvnd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  CLOUDSMITH_ORG: globex-innovations
  CLOUDSMITH_REPO: acme-nonprod
  SERVICE: ci_acme_service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out
      - uses: actions/checkout@v4

      # 2) Set up Java 11
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      # 3) Install Maven Daemon (mvnd)
      - name: Install mvnd
        run: |
          brew tap mvndaemon/homebrew-mvnd
          # for Maven 3.9.x compatibility:
          brew install mvnd@1
          # OR, to try the Maven 4 RC build:
          # brew install mvnd

      # 4) Authenticate to Cloudsmith via OIDC
      - name: Auth to Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only: 'true'
          pip-install: false

      # 5) Write settings.xml (mirrorOf=central so mvnd still proxies Central → Cloudsmith → Central upstream)
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'EOF'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>cloudsmith</id>
                <username>${{ env.SERVICE }}</username>
                <password>${{ secrets.CLOUDSMITH_API_KEY }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>cloudsmith</id>
                <name>Cloudsmith – mirror of Central</name>
                <url>https://maven.cloudsmith.io/${{ env.CLOUDSMITH_ORG }}/${{ env.CLOUDSMITH_REPO }}/</url>
                <mirrorOf>*,!central</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

      # 6) Cache your Maven repo between runs
      - name: Cache ~/.m2/repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 7) Pre-fetch dependencies
      - name: mvnd go-offline
        run: mvnd dependency:go-offline --settings ~/.m2/settings.xml

      # 8) Build with mvnd
      - name: Build with mvnd
        run: mvnd -T1C -Dmaven.artifact.threads=12 clean verify --settings ~/.m2/settings.xml -U

      # 9) Deploy
      - name: Deploy to Cloudsmith
        run: mvnd deploy --settings ~/.m2/settings.xml
