name: Java CI and Deploy to Cloudsmith

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDSMITH_ORG: globex-innovations
  CLOUDSMITH_REPO: acme-nonprod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      # 3) Clear local Maven cache (optional)
      - name: Clear Maven cache
        run: rm -rf ~/.m2/repository/*

      # 4) Configure Maven settings (Pull & Push to Cloudsmith)
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>cloudsmith</id>
                <username>ciara-carey</username>
                <password>${{ secrets.CLOUDSMITH_API_KEY }}</password>
              </server>
            </servers>
          </settings>
          EOF
          
      # Debug: Show Maven settings to verify correctness (remove before production)
      - name: Debug Generated Maven Settings
        run: cat ~/.m2/settings.xml

      # 5) Build with Maven
      - name: Build with Maven
        run: mvn -X clean package --settings ~/.m2/settings.xml -U
        
      # 6) Deploy to Cloudsmith
      - name: Deploy to Cloudsmith
        run: mvn -B deploy --settings ~/.m2/settings.xml
