name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate SBOM
      run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: bom.xml
        path: target/bom.xml

    - name: Deploy to Cloudsmith
      run: mvn -B deploy --settings .github/workflows/maven-settings.xml
      env:
        CLOUDSMITH_USERNAME: ciara-carey
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
        CLOUDSMITH_REPOSITORY: ${{ secrets.CLOUDSMITH_REPOSITORY }}
        #CLOUDSMITH_REPOSITORY_URL: "https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_TOKEN }}/${{ secrets.CLOUDSMITH_REPOSITORY }}/maven/"
        CLOUDSMITH_REPOSITORY_URL: https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/ciara-demo/ciara-test/maven/
