name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDSMITH_REPO_NAME: ciara-demo/sbom-support
  CLOUDSMITH_USERNAME: ciara-carey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -X clean package --settings ~/.m2/settings.xml -U
      env:
        CLOUDSMITH_USERNAME: ${{ env.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_ENTITLEMENT_TOKEN: ${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}
        CLOUDSMITH_REPOSITORY_URL: "https://maven.cloudsmith.io/${{ env.CLOUDSMITH_REPO_NAME }}"      
        DL_CLOUDSMITH_REPOSITORY_URL: "https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/"

    - name: Generate SBOM
      run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom --settings ~/.m2/settings.xml

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: bom.xml
        path: target/bom.xml

    - name: Deploy to Cloudsmith
      run: mvn -B deploy --settings ~/.m2/settings.xml
      env:
        CLOUDSMITH_USERNAME: ${{ env.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_ENTITLEMENT_TOKEN: ${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}
        CLOUDSMITH_REPOSITORY_URL: "https://maven.cloudsmith.io/${{ env.CLOUDSMITH_REPO_NAME }}"      
        DL_CLOUDSMITH_REPOSITORY_URL: "https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/"
