name: Java CI and Deploy to Cloudsmith

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write      # GH OIDC → Cloudsmith

env:
  CLOUDSMITH_ORG:  globex-innovations
  CLOUDSMITH_REPO: acme-nonprod
  SERVICE:          ci_acme_service   # service-account slug

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Check out code
    - uses: actions/checkout@v4

    # 2. JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin      # “adopt” is deprecated

    # 3. (optional) clear local cache
    - run: rm -rf ~/.m2/repository/*

    # 4a. Get an OIDC-based **ephemeral** API key
    - name: Auth to Cloudsmith with OIDC
      id: cs-auth
      uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
      with:
        oidc-namespace:    ${{ env.CLOUDSMITH_ORG }}
        oidc-service-slug: ${{ env.SERVICE }}
        oidc-auth-only:    'true'
        pip-install:       false
        # exports CLOUDSMITH_API_KEY for the next steps

    # 4b. Generate Maven settings with a global mirror
    - name: Configure Maven settings for Cloudsmith
      shell: bash
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
 
          <servers>
            <server>
              <id>cloudsmith</id>
              <username>${SERVICE}</username>
              <password>${CLOUDSMITH_API_KEY}</password>
            </server>
          </servers>
        </settings>
        EOF
        echo "----- ~/.m2/settings.xml -----"
        cat ~/.m2/settings.xml

    # 5. Build
    - name: Build (clean package)
      run: mvn -B --settings ~/.m2/settings.xml clean package

    # 6. Deploy to Cloudsmith (needs <distributionManagement> in the POM **or** an alt-repo flag)
    - name: Deploy
      run: >
        mvn -B --settings ~/.m2/settings.xml
        -DaltDeploymentRepository=cloudsmith::default::https://dl.cloudsmith.io/${{ env.CLOUDSMITH_ORG }}/${{ env.CLOUDSMITH_REPO }}/maven/
        deploy
