name: Java CI and Deploy to Cloudsmith

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: read
  id-token: write  # Necessary for GH Identity Provider to write the JWT token which Cloudsmith needs to read

env:
  CLOUDSMITH_ORG: cloudsmith-test
  #cloudsmith-test 
  #globex-innovations
  CLOUDSMITH_REPO: acme3
  SERVICE: oidc_ciara
  #ci_acme_service
  #oidc_ciara 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout
    - name: Check out repo
      uses: actions/checkout@v4

    # 2) JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"

    # 3) Authenticate to Cloudsmith via OIDC
    - name: Cloudsmith OIDC login
      uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
      with:
        oidc-namespace: ${{ env.CLOUDSMITH_ORG }}
        oidc-service-slug: ${{ env.SERVICE }}
        oidc-auth-only: "true"
        pip-install: false   # we’re not using pip here

    # 4) Write ~/.m2/settings.xml  
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
          <servers>
            <server>
              <id>cloudsmith</id>
              <username>${{ env.SERVICE }}</username>
              <password>${CLOUDSMITH_API_KEY}</password>
            </server>
          </servers>

          <mirrors>
            <!-- Mirror *everything* through Cloudsmith except the repo whose id is 'central'. -->
            <mirror>
              <id>cloudsmith</id>
              <name>Cloudsmith mirror</name>
              <url>https://maven.cloudsmith.io/${{ env.CLOUDSMITH_ORG }}/${{ env.CLOUDSMITH_REPO }}/</url>
              <mirrorOf>*,!central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

    # 5) Build + unit tests
    - name: Build with Maven
      run: mvn -B clean verify --settings ~/.m2/settings.xml -U

    # 6) Deploy the artifact to Cloudsmith
    #    altDeploymentRepository overrides <distributionManagement> and avoids POM edits.
    - name: Deploy to Cloudsmith
      run: |
        mvn -B deploy \
            -DaltDeploymentRepository=cloudsmith::default::https://maven.cloudsmith.io/${{ env.CLOUDSMITH_ORG }}/${{ env.CLOUDSMITH_REPO }}/ \
            --settings ~/.m2/settings.xml
