name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLOUDSMITH_REPO_NAME: ciara-demo/sbom-support
  CLOUDSMITH_USERNAME: ciara-carey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Clear local Maven repository cache
      run: rm -rf ~/.m2/repository/*
        
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>cloudsmith</id>
              <username>${{ secrets.CLOUDSMITH_USERNAME }}</username>
              <password>${{ secrets.CLOUDSMITH_API_KEY }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>cloudsmith-profile</id>
              <pluginRepositories>
                <pluginRepository>
                  <id>cloudsmith</id>
                  <name>cloudsmith</name>
                  <url>https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/</url>
                  <releases>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                  </releases>
                  <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                  </snapshots>
                </pluginRepository>
              </pluginRepositories>
              <repositories>
                <repository>
                  <id>cloudsmith</id>
                  <name>cloudsmith</name>
                  <url>https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/</url>
                  <releases>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                  </releases>
                  <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                  </snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>cloudsmith-profile</activeProfile>
          </activeProfiles>
        </settings>
        EOF

    - name: Build with Maven
      run: mvn -X clean package --settings ~/.m2/settings.xml -U
      env:
        CLOUDSMITH_USERNAME: ${{ env.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_ENTITLEMENT_TOKEN: ${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}
        CLOUDSMITH_REPOSITORY_URL: "https://maven.cloudsmith.io/${{ env.CLOUDSMITH_REPO_NAME }}"      
        DL_CLOUDSMITH_REPOSITORY_URL: "https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/"

    - name: Generate SBOM
      run: mvn -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom --settings ~/.m2/settings.xml

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: bom.xml
        path: target/bom.xml

    - name: Deploy to Cloudsmith
      run: mvn -B deploy --settings ~/.m2/settings.xml
      env:
        CLOUDSMITH_USERNAME: ${{ env.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        CLOUDSMITH_ENTITLEMENT_TOKEN: ${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}
        CLOUDSMITH_REPOSITORY_URL: "https://maven.cloudsmith.io/${{ env.CLOUDSMITH_REPO_NAME }}"      
        DL_CLOUDSMITH_REPOSITORY_URL: "https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT_TOKEN }}/${{ env.CLOUDSMITH_REPO_NAME }}/maven/"
        
