name: Update Cloudsmith API Key for Dependabot

on:
  # This will run at the schedule you define
  schedule:
    - cron: "*/30 * * * *"  # Update every 30 minutes
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-cloudsmith-api-key:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the Cloudsmith CLI Action to authenticate via OIDC and get the token
      - name: Install Cloudsmith CLI and Authenticate via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'ciara-demo'
          oidc-service-slug: 'gha-service'
      
      # Update the Dependabot secret with the new API Key using the fine-grained token
      - name: Update Dependabot Secret
        uses: merchstack/set-action-dependabot-secret@v/2.1.3
        with:
          name: 'DEP_CLOUDSMITH_API_KEY'
          value: ${{ env.CLOUDSMITH_API_KEY }}
          repository: ciaracarey/my-maven-project
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
