name: Update Cloudsmith API Key for Dependabot

on:
  # This will run at the schedule you define
  schedule:
    - cron: "0 */11 * * *"  # Update every 11 hours
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-cloudsmith-api-key:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for OIDC
      contents: write  # Ensures access to repository content

    steps:
      # Use the Cloudsmith CLI Action to authenticate via OIDC and get the token
      - name: Install Cloudsmith CLI and Authenticate via OIDC
        id: cloudsmith-auth
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'ciara-demo'
          oidc-service-slug: 'gha-service'

     # Set the Cloudsmith API key as a Dependabot secret using GitHub CLI
      - name: Rotate Dependabot Secret          
        env:
          CLOUDSMITH_API_KEY: "${{ steps.cloudsmith-auth.outputs.cloudsmith_jwt }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh secret set DEP_CLOUDSMITH_API_KEY \
            --app dependabot \
            --repo ${{ github.repository }} \
            --body "$CLOUDSMITH_API_KEY"
