name: Rotate Dependabot Secret

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes

jobs:
  rotate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (LibSodium for encryption)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev
          npm install tweetsodium

      - name: Fetch public key for Dependabot secrets
        id: fetch_public_key
        run: |
          public_key_json=$(gh api /orgs/ciara-demo/dependabot/secrets/public-key -H "Accept: application/vnd.github+json")
          echo "key=$(echo $public_key_json | jq -r '.key')" >> $GITHUB_ENV
          echo "key_id=$(echo $public_key_json | jq -r '.key_id')" >> $GITHUB_ENV

      - name: Encrypt the secret using LibSodium
        id: encrypt_secret
        run: |
          node -e "
            const sodium = require('tweetsodium');
            const key = Buffer.from('${{ env.key }}', 'base64');
            const secret = Buffer.from('${{ secrets.YOUR_NEW_SECRET }}');
            const encryptedBytes = sodium.seal(secret, key);
            console.log(Buffer.from(encryptedBytes).toString('base64'));
          " > encrypted_secret.txt
          echo "encrypted_value=$(cat encrypted_secret.txt)" >> $GITHUB_ENV

      - name: Rotate Dependabot secret using GitHub CLI
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          /orgs/ciara-demo/dependabot/secrets/DEP_CLOUDSMITH_API_KEY \
          -f "encrypted_value=${{ env.encrypted_value }}" \
          -f "key_id=${{ env.key_id }}" \
          -f "visibility=selected" \
          -f "selected_repository_ids[]=815194697"
