name: Update Cloudsmith API Key for Dependabot

on:
  schedule:
    - cron: "0 */11 * * *"  # Update every 11 hours
  workflow_dispatch:

jobs:
  update-cloudsmith-api-key:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for OIDC
      contents: read   # Ensures access to repository content

    steps:
      # Step 1: Use the Cloudsmith CLI Action to authenticate via OIDC and get the token
      - name: Install Cloudsmith CLI and Authenticate via OIDC
        id: cloudsmith-auth
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'ciara-demo'
          oidc-service-slug: 'gha-service'

      # Step 2: Rotate the Dependabot Secret using the Cloudsmith JWT and Fine-Grained PAT
      - name: Update Dependabot Secret
        env:
          #CLOUDSMITH_API_KEY: "${{ steps.cloudsmith-auth.outputs.cloudsmith_jwt }}"
          GH_TOKEN: "${{ secrets.FINE_GRAINED_PAT }}"
        run: |
          gh secret set DEP_CLOUDSMITH_API_KEY \
            --app dependabot \
            --visibility all 
            --repo "${{ github.repository }}" \
            --body "$CLOUDSMITH_API_KEY"
