name: Update Cloudsmith API Key for Dependabot

# Run the workflow on a schedule or manually
on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:  # Allows for manual runs

jobs:
  update-cloudsmith-api-key:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for OIDC
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate with Cloudsmith using OIDC and get API Key
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'ciara-demo'  # Your OIDC namespace
          oidc-service-slug: 'gha-service'  # Your OIDC service slug

      # Set the Dependabot Secret for DEP_CLOUDSMITH_API_KEY with the updated Cloudsmith API Key
      - name: Set Dependabot Secret for Cloudsmith API Key
        uses: merchstack/set-action-dependabot-secret@v/2.1.3
        with:
          name: 'DEP_CLOUDSMITH_API_KEY'  # Name of the Dependabot secret to update
          value: ${{ env.CLOUDSMITH_API_KEY }}  # Use the API key retrieved by the Cloudsmith CLI action
          repository: ${{ github.repository }}  # The current repository
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use a PAT with appropriate permissions
          dependabot: true  # Indicate this is a Dependabot secret

