name: Update Cloudsmith API Key for Dependabot

on:
  # Schedule the workflow to run every 30 minutes
  #schedule:
  #  - cron: "*/30 * * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-cloudsmith-api-key:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necessary for OIDC
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # OIDC token retrieval and authentication with Cloudsmith
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'ciara-demo'  # Your OIDC namespace
          oidc-service-slug: 'gha-service'  # Your OIDC service slug

      # Set the Cloudsmith API Key as a Dependabot secret
      - name: Set Dependabot Secret for Cloudsmith API Key
        uses: merchstack/set-action-dependabot-secret@v/2.1.3
        with:
          name: 'CLOUDSMITH_API_KEY'  # The name of the secret for Dependabot
          value: ${{ secrets.CLOUDSMITH_API_KEY }}  # Use the API key provided by the Cloudsmith CLI action
          repository: ${{ github.repository }}  # The current repository
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use your PAT instead of GITHUB_TOKEN
          dependabot: true  # Mark as a Dependabot secret
